cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('main_cart', views.main_cart, name='cart'),

    path('create/<slug:slug>', views.create_cart, name='create_cart'),
    path('delete/<int:product_id>', views.delete_cart, name='delete_cart'),
    path('empty_cart', views.empty_cart, name='empty_cart'),
    path('order/', views.create_order, name='create_order'),
]

guitarst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('user.urls', namespace='user')),
]

from guitarst import settings

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('register/', views.register_view.as_view(), name = 'register'),
    path('reg_or_auth/', views.reg_or_auth_view, name = 'reg_or_auth'),
    path('profile/<int:pk>', views.profile_view, name = 'profile'),
    path('add_email/', views.add_email, name = 'add_email'),
    path('delete_email/', views.delete_email, name='delete_email'),
]

user/models.py
from django.db import models

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
from django.core.validators import *
from django.core.exceptions import *

class person_form(forms.Form):
    login = forms.CharField(max_length=100, label='Логин', widget=forms.TextInput(attrs={
            'class': 'auth-f',
            'placeholder': 'Введите логин',
        }))
    password = forms.CharField(max_length=100, label='Пароль', widget=forms.PasswordInput(attrs={
            'class': 'auth-f1',
            'placeholder': 'Введите пароль',
        }))


class register_form(UserCreationForm):
    username = forms.CharField(max_length=120, label='Логин', widget=forms.TextInput(attrs={
        'class': 'username', 'placeholder': 'Введите логин'}))
    
    password1 = forms.CharField(max_length=120, label='Пароль', widget=forms.PasswordInput(attrs={
        'class': 'password1', 'placeholder': 'Придумайте пароль'}))
    
    password2 = forms.CharField(max_length=120, label='Повтор пароля', widget=forms.PasswordInput(
        attrs={'class': 'password2', 'placeholder': 'Повторите пароль'}))

    class Meta: 
        model = User
        fields = ('username', 'password1', 'password2')

class add_email_form(forms.Form):
    email = forms.EmailField(max_length=120, label='Почта', widget=forms.EmailInput(attrs={'placeholder': 'Введите почту'}))

user/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import *
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import *
from django.core.validators import *
from cart.models import *

# Регистрация или вход
def reg_or_auth_view(request):
    context = {
        'title': 'Reg_or_auth',
        'button1': 'Авторизация',
        'button2': 'Регистрация',
    }

    return render(request, 'reg_or_auth.html', context)


# Логин
def login_view(request):
    if request.method == 'POST':
        form = person_form(request.POST)
        if form.is_valid():
            username = request.POST['login']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('catalog:Main')

    else:
        form = person_form()
            
    context = {
        'form': form,
    }
    return render(request, 'auth.html', context)


# Выход
def logout_view(request):
    logout(request)
    return redirect('user:login')


# Регистрация
class register_view(CreateView):
    template_name = 'register.html'
    form_class = register_form
    success_url = reverse_lazy('catalog:Main')


# Профиль пользователя
def profile_view(request, pk):
    user = User.objects.filter(pk=pk)# Пользователь
    try:
        order = order_Model.objects.filter(user=request.user)# Заказ
        address = order.values('address')[0]['address']# Адрес
        first_name = order.values('first_name')[0]['first_name']# Имя
        last_name = order.values('last_name')[0]['last_name']# Фамилия
        status = order.values('status')[0]['status']# Статус

    except:
        print('Нет заказов')
        address = 'address'
        first_name = 'first_name'
        last_name = 'last_name'
        status = 'status'
        order_products = 'order_products'

    order_products = []# Заказанные товары
    for i in order_products_Model.objects.all():
        order_products.append(i.product)
    
    username = user.values('username')[0]['username']# Имя пользователя
    if user.values('email').exists():
        email = user.values('email')[0]['email']# Почта

    context = {
        'username': username,
        'email': email,
        'address': address,
        'first_name': first_name,
        'last_name': last_name,
        'status': status,
        'order_products': order_products,
    }
    
    return render(request, 'profile.html', context)


# Добавление почты
def add_email(request):
    if request.method == 'POST':
        form = add_email_form(request.POST)
        if form.is_valid():
        
            email = form.cleaned_data['email']
            user = User.objects.filter(username=request.user)
            user.update(email=email)
        
            return redirect('user:profile', user.values('id')[0]['id'])
        
    else:
        form = add_email_form()

    context = {
        'form': form,
    }

    return render(request, 'email.html', context)
    

# Удаление почты
def delete_email(request):
    user = User.objects.filter(username=request.user)
    user = user.values('email').update(email='')

    return redirect(request.META['HTTP_REFERER'])

user/templates/auth.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/user.css "%}"> 
{% endblock %}

{% block body %}
    <div class="auth">
        <div class="auth__header"> Авторизация </div>
        <form class="auth__per-form" method="POST" action="{% url 'user:login' %}">
            {% csrf_token %}
            {{ form }}
        <input class="auth__auth-input" type="submit" value="Войти">
        </form>
    </div>
{% endblock %}

user/templates/email.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/user.css" %}">
{% endblock %}

{% block body %}
    <!-- <form class="add_email_form" action="{% url "user:add_email" %}" method="post">
        {% csrf_token %}
        <input class="add_email__text" type="text" name="email_data">
        <input class="add_email__button" type="submit" value="Добавить почту">
    </form> -->
    <form class="add_email_form" action="{% url "user:add_email" %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="add_email_form__form_group">
                {{ field.label }}
                {{ field }}
                {% if field.errors %}
                    <div class="form_group__errors">{{ field.errors }}</div>
                {% endif %}
            </div>
        {% endfor %}
        <input class="add_email_form__input" type="submit" value="Добавить почту">
    </form>
{% endblock %}

user/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/user.css" %}">
{% endblock %}

{% block body %}
    <style>
        .success {
            font-family: 'JetBrains Mono', sans-serif;
            font-size: 30px;
            background: green; 
            display: flex ;
            justify-content: center;
        }

        .message_wrapper {
            width: 100%;
            float: left;
            margin: 0;
        }
    </style>
    <div class="message_wrapper">
        {% if messages %}
            {% for message in messages %}
                <div class="{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
    </div>
    <h2 class="profile_username">Имя пользователя: {{ username }}</h2>
    {% if email %}
        <h2 class="profile_email">Почта: {{ email }}</h2>
        <form action="{% url "user:delete_email" %}">
            <input class="delete_email_button" type="submit" value="Удалить почту">
        </form>
        <form action="{% url "user:logout" %}">
            <input class="logout_button" type="submit" value="Выйти">
        </form>
    {% else %}
        <h2 class="add_email">Почта не добавлена</h2>
        <form action="{% url "user:add_email" %}">
            <input class="add_email_button" type="submit" value="Добавить почту">
        </form>
        <form action="{% url "user:logout" %}">
            <input class="logout_button" type="submit" value="Выйти">
        </form>
    {% endif %}
    {% if order_products %}
        <div class="orders_wrapper">
            <h2 class="orders_wrapper__title">Заказы</h2>
            <h2 class="orders_wrapper__name">Имя и фамилия получателя: {{ first_name }} {{ last_name }}</h2>
            <h2 class="orders_wrapper__address">Адрес доставки: {{ address }}</h2>
            <h2 class="orders_wrapper__status">Статус заказа: {{ status }}</h2>
            <h2 class="orders_wrapper__products">Товары:</h2>
            {% for product in order_products %}
                <h3 class="order_wrapper__product">{{ product }}</h3>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

user/templates/reg_or_auth.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/user.css" %}">
{% endblock %}

{% block body %}
    <div class="buttons_container">
        <form action="{% url 'user:login' %}">
            <button class="login_button">{{ button1 }}</button>
        </form>
        <form action="{% url 'user:register' %}">
            <button class="reg_button">{{ button2 }}</button>
        </form>
    </div>
{% endblock %}

user/templates/register.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/user.css" %}">
{% endblock %}

{% block body %}
    <form class="form_reg" method='post' action="{% url 'user:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form_reg__button" type="submit" value="Зарегистрироваться">
    </form>
{% endblock %}