cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('main_cart', views.main_cart, name='cart'),

    path('create/<slug:slug>', views.create_cart, name='create_cart'),
    path('delete/<int:product_id>', views.delete_cart, name='delete_cart'),
    path('empty_cart', views.empty_cart, name='empty_cart'),
    path('order/', views.create_order, name='create_order'),
]

catalog/urls.py
from django.urls import path, include
from catalog import views

app_name = 'catalog'

guitar_patterns = [
    path('acoustic_gt/', views.ac_gt, name = 'Ac_gt'),
    path('bass_gt/', views.bass_gt, name = 'Bass_gt'),
    path('electro_gt/', views.electro_gt, name = 'Electro_gt'),
]

dops_patterns = [
    path('strings/', views.strings, name = 'Strings'),
    path('mediators/', views.mediators, name = 'Mediators'),
    path('capo/', views.capo, name = 'Capo'),
    path('others/', views.others, name = 'Others'),
]

urlpatterns = [
    path('', views.main, name = 'Main'),
    path('dops/', views.dops, name = 'Dops'),
    path('dops/', include(dops_patterns)),
    path('guitars/', views.guitars_ListView.as_view(), name = 'Guitars'),
    path('guitars/', include(guitar_patterns)),

    path('extra_inf/<int:pk>', views.extra_inf, name = 'extra_inf'),
]

guitarst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('user.urls', namespace='user')),
]

from guitarst import settings

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('register/', views.register_view.as_view(), name = 'register'),
    path('reg_or_auth/', views.reg_or_auth_view, name = 'reg_or_auth'),
    path('profile/<int:pk>', views.profile_view, name = 'profile'),
    path('add_email/', views.add_email, name = 'add_email'),
    path('delete_email/', views.delete_email, name='delete_email'),
]

catalog/models.py
from django.db import models

#Товары
class pproducts(models.Model):
    name = models.CharField(max_length = 25, verbose_name = 'Название')
    description = models.TextField(blank = True, null =  True, verbose_name = 'Описание')
    price = models.DecimalField(max_digits = 8, decimal_places = 2, verbose_name = 'Цена')
    quantity = models.PositiveIntegerField(default = 0, verbose_name = 'Количество')
    image = models.ImageField(upload_to = 'images', blank = True, null =  True, verbose_name = 'Изображение')
    slug = models.SlugField(max_length = 200, unique = True, blank = True, null = True, verbose_name = 'URL')
    category = models.TextField(max_length = 50, blank = True, null = True, verbose_name = 'Категория')

    class Meta():
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name


#Категории товаров
class categories(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to = 'images', blank = True, null = True)
    slug = models.SlugField(max_length = 200, unique = True, blank = True, null = True, verbose_name = 'URL')
    category = models.TextField(max_length = 50, blank = True, null = True)
    url_name = models.TextField(max_length = 25, blank = True, null = True)

    class Meta():
        db_table = 'categories'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'


    def __str__(self):
        return self.name

catalog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from .models import pproducts, categories
from django.views.generic import ListView
from django.contrib.auth.models import User
from django.core.paginator import Paginator


# Каталог
def main(request):
    context = {
        'title': 'Main',
        'request': request,
    }

    return render(request, 'main.html', context)


# Гитары
class guitars_ListView(ListView):
    model = categories
    context_object_name =  'categories'
    template_name = 'Guitars.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Guitars'
        context['title1'] = 'Гитары'
        return context


# Функция для пагинации
def get_pagination(model, request, category):
    model = model

    products = model.objects.filter(category=category)

    pagination = Paginator(products, 4)# разбиение по страницам
    page_number = request.GET.get('page')# количество страниц
    page = pagination.get_page(page_number)# страница для отображения
    return [page, pagination]


# Акустические гитары
def ac_gt(request):
    pagin = get_pagination(pproducts, request, category='ac-gt')
    
    products = pagin[0]
    paginator = pagin[1]
    for product in products:
        print(product.image.url)
    
    context = {
        'title': 'Acoustic Guitars',
        'title1': 'Акустические гитары',
        'products': products,
        'paginator': paginator,
    }

    return render(request, 'ac_gt.html', context)


# Бас гитары
def bass_gt(request):
    pagin = get_pagination(pproducts, request, category='bass-gt')

    products = pagin[0]
    paginator = pagin[1]

    context = {
        'title': 'Bass Guitars',
        'title1': 'Бас гитары',
        'products': products ,
        'paginator': paginator, 
    }

    return render(request, 'bass_gt.html', context)


# Электро гитары
def electro_gt(request):
    pagin = get_pagination(pproducts, request, category='el-gt')

    products = pagin[0]
    paginator = pagin[1]

    context = {
        'title': 'Electro Guitars',
        'products': products,
        'paginator': paginator,
    }

    return render(request, 'electro_gt.html', context)


# Аксессуары
def dops(request):
    categorys = categories.objects.all()

    context = {
        'title': 'Accessories',
        'title1': 'Аксессуары',
        'categories': categorys
    }

    return render(request, 'dops.html', context)


# Струны
def strings(request):
    pagin = get_pagination(pproducts, request, category='strings')

    products = pagin[0]
    paginator = pagin[1]

    context = {
        'title': 'Strings',
        'title1': 'Струны',
        'products': products,
        'paginator': paginator,
    }

    return render(request, 'dops/strings.html', context)


# Медиаторы
def mediators(request):
    pagin = get_pagination(pproducts, request, category='mediators')

    products = pagin[0]
    paginator = pagin[1]

    context = {
        'title': 'Mediators',
        'title1': 'Медиаторы',
        'products': products,
        'paginator': paginator,
    }

    return render(request, 'dops/mediators.html', context)


# Каподастры
def capo(request):
    pagin = get_pagination(pproducts, request, category='capo')

    products = pagin[0]
    paginator = pagin[1]

    context = {
        'title': 'Capo',
        'title1': 'Каподастры',
        'products': products,
        'paginator': paginator,
    }

    return render(request, 'dops/capo.html', context)
    

# Другие товары
def others(request):
    pagin = get_pagination(pproducts, request, category='others')

    products = pagin[0]
    paginator = pagin[1]

    context = {
        'title': 'Others',
        'title1': 'Другое',
        'products': products,
        'paginator': paginator,
    }

    return render(request, 'dops/others.html', context)


# Доп информация о товаре
def extra_inf(request, pk):
    product = pproducts.objects.filter(pk=pk)
    
    context = {
        'name': product.values('name')[0]['name'],
        'price': product.values('price')[0]['price'],
        'quantity': product.values('quantity')[0]['quantity'],
        'description': product.values('description')[0]['description'],
        'product': product,
        'title1': 'Описание',
        'title2': 'Наличие',
        'title3': 'Цена',
        'no_product': 'Нет в наличии',
    }

    return render(request, 'extra_inf.html', context)

catalog/templates/Guitars.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/style.css "%}">
{% endblock %}

{% block body %}
    <div class="guitars">
        <div class="gt"> {{ title1 }} </div>
        <div class="wrapper">
            {% for category in categories %}
            {% if category.category == "guitars" %}
                <div class="card">
                    <a class="card__link" href="{% url category.url_name %}">
                        {% if category.image %}
                            <img src="{{ category.image.url }}" class="card__image">
                            <p> {{ category.name }} </p>
                        {% else %}
                            <img src="{% static "images/not.found.jpg" %}" class="card__image">
                        {% endif %}
                    </a>
                </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/ac_gt.html
{% extends "base_product.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/style.css" %}">
{% endblock %}

{% block product %}
    <div class="ac-gt">{{ title1 }}</div>
    <div class="wrapper">
        {% for product in products %}
        {% if product.category == "ac-gt" %}
            <div class="card">
                <a class="card__link" href="{% url "catalog:extra_inf" product.pk %}">
                    {% if product.image %}
                        <img src="{{ product.image.url }}" class="card__image">
                        <div class="card__title"> {{ product.name }} </div>
                        <div class="card_price"> {{ product.price }}руб</div>
                        <a class="in_cart" href="{% url 'cart:create_cart' product.slug %}">В корзину</a>
                    {% else %}
                        <img src="{% static "images/not.found.jpg" %}" class="card__image">
                    {% endif %}
                </a>
            </div>
        {% endif %}
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block link %}{% endblock %}
    <title> {{ title }} </title>
</head>
<body class="body">
    <header class="header">
        <div class="catalog"><a class="ul__link" href="{% url 'catalog:Main' %}">Каталог</div>
        <nav class="nav">
            <ul class="ul">
                <li class="ul__li"><a class="ul__link" href="{% url 'catalog:Guitars' %}">Гитары</a></li>
                <li class="ul__li"><a class="ul__link" href="{% url 'catalog:Dops' %}">Аксесуары и комплектующие</a></li>
                {% if request.user.is_authenticated %}
                    <li class="ul__li"><a class="ul__link" href="{% url 'user:profile' user.pk %}">Аккаунт</a></li>
                {% else %}
                    <li class="ul__li"><a class="ul__link" href="{% url 'user:reg_or_auth' %}">Регистрация и вход</a></li>
                {% endif %}
                <li class="ul__li"><a class="ul__link" href="{% url 'cart:cart' %}">Корзина</a></li>
            </ul>
        </nav>
    </header>
    {% block body %}{% endblock %}
</body>
</html>

catalog/templates/base_catalog.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block link %}{% endblock %}
    <title> {{ title }} </title>
</head>

{% block body %}{% endblock %}
</html>

catalog/templates/base_product.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block link %}{% endblock %}
    <title> {{ title }} </title>
</head>
<body class="body">
    <header class="header">
        <div class="catalog"><a class="ul__link" href="{% url 'catalog:Main' %}">Каталог</div>
        <nav class="nav">
            <ul class="ul">
                <li class="ul__li"><a class="ul__link" href="{% url 'catalog:Guitars' %}">Гитары</a></li>
                <li class="ul__li"><a class="ul__link" href="{% url 'catalog:Dops' %}">Аксесуары и комплектующие</a></li>
                {% if request.user.is_authenticated %}
                    <li class="ul__li"><a class="ul__link" href="{% url 'user:profile' user.pk %}">Аккаунт</a></li>
                {% else %}
                    <li class="ul__li"><a class="ul__link" href="{% url 'user:reg_or_auth' %}">Регистрация и вход</a></li>
                {% endif %}
                <li class="ul__li"><a class="ul__link" href="{% url 'cart:cart' %}">Корзина</a></li>
            </ul>
        </nav>
    </header>
    {% block product %}{% endblock %}
    {% if products.has_other_pages %}
        <div class="pagination_wrapper">
            <nav class="pagination_nav">
                <ul class="pagination_ul"> 
                    {% if products.has_previous %}
                        <li class="pagination_li"><a class="pagination_link_prev" href="?page={{ p.previous_page_number }}">&#8592;</a></li>
                    {% endif %}

                    {% for p in paginator.page_range %}
                        {% if products.number == p %}
                            <li class="pagination_li"><a class="pagination_link_select">{{ p }}</a></li>
                        {% elif p >= products.number|add:-2 and p <= products.number|add:2 %}
                            <li class="pagination_li"><a class="pagination_link" href="?page={{ p }}">{{ p }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if products.has_next %}
                        <li class="pagination_li"><a class="pagination_link_next" href="?page={{ products.next_page_number }}">&#8594;</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    {% endif %}
</body>
</html>

catalog/templates/bass_gt.html
{% extends "base_product.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/style.css" %}">
{% endblock %}

{% block product %}
    <div class="bass-gt">{{ title1 }}</div>
    <div class="wrapper">
        {% for product in products %}
            {% if product.category == "bass-gt" %}
                <div class="card">
                    <a class="card__link" href="{% url "catalog:extra_inf" product.pk %}">
                        {% if product.image %}
                            <img src="{{ product.image.url }}" class="card__image">
                            <div class="card__title"> {{ product.name }} </div>
                            <div class="card_price"> {{ product.price }}руб</div>
                            <a class="in_cart" href="{% url 'cart:create_cart' product.slug %}">В корзину</a>
                        {% else %}
                            <img src="{% static "images/not.found.jpg" %}" class="card__image">
                        {% endif %}
                    </a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/dops.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/style.css" %}">  
{% endblock %}
   
{% block body %}
    <div class="dops">
        <div class="dops_title"> {{ title1 }} </div>
        <div class="wrapper">
            {% for category in categories %}
            {% if category.category == "dops" %}
                <div class="card">
                    <a class="card__link" href="{% url category.url_name %}">
                        {% if category.image %}
                            <img src="{{ category.image.url }}" class="card__image">
                            <p> {{ category.name }} </p>
                        {% else %}
                            <img src="{% static "images/not.found.jpg" %}" class="card__image">
                        {% endif %}
                    </a>
                </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/electro_gt.html
{% extends "base_product.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/style.css" %}">
{% endblock %}

{% block product %}
    <div class="el-gt"> Электрогитары </div>
    <div class="wrapper">
        {% for product in products %}
        {% if product.category == "el-gt" %}
            <div class="card">
                <a class="card__link" href="{% url "catalog:extra_inf" product.pk %}">
                    {% if product.image %}
                        <img src="{{ product.image.url }}" class="card__image">
                        <div class="card__title"> {{ product.name }} </div>
                        <div class="card_price"> {{ product.price }}руб</div>
                        <a class="in_cart" href="{% url 'cart:create_cart' product.slug %}">В корзину</a>
                    {% else %}
                        <img src="{% static "images/not.found.jpg" %}" class="card__image">
                    {% endif %}
                </a>
            </div>
        {% endif %}
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/extra_inf.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/style.css" %}">
{% endblock %}

{% block body %}
    <h1 class="product_name">{{ name }}</h1>
    {% if product %}
        <div class="product_image_wrapper">
            <img class="product_image" src="{{ product.0.image.url }}">
            <div class="product_button_wrapper">
                <a class="product_button" href="{% url 'cart:create_cart' product.0.slug %}">В корзину</a>
            </div>
        </div>
    {% else %}
        <div class="product_image_wrapper">
            <img src="{% static "images/not.found.jpg" %}" class="product_image_error">
        </div>
    {% endif %}
    <h2 class="product_des_name">{{ title1 }}</h2>
    <div class="product_des">{{ description }}</div>
    <h2 class="product_quantity_name">{{ title2 }}</h2>
    {% if quantity != 0 %}
        <div class="product_quantity">{{ quantity }}</div>
    {% else %}
        <div class="product_quantity">{{ no_product }}</div>
    {% endif %}
    <h2 class="product_price_name">{{ title3 }}</h2>
    <div class="product_price">{{ price }}</div> 
{% endblock %}

catalog/templates/main.html
{% extends "base_catalog.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/style.css "%}">
{% endblock %}

{% block body %}
    <body class="body">
        <header class="header">
            <div class="catalog"><a class="ul__link" href="{% url 'catalog:Main' %}">Каталог</div>
            <nav class="nav">
                <ul class="ul">
                    <li class="ul__li"><a class="ul__link" href="{% url 'catalog:Guitars' %}">Гитары</a></li>
                    <li class="ul__li"><a class="ul__link" href="{% url 'catalog:Dops' %}">Аксесуары и комплектующие</a></li>
                    {% if request.user.is_authenticated %}
                        <li class="ul__li"><a class="ul__link" href="{% url 'user:profile' user.pk %}">Аккаунт</a></li>
                    {% else %}
                        <li class="ul__li"><a class="ul__link" href="{% url 'user:reg_or_auth' %}">Регистрация и вход</a></li>
                    {% endif %}
                    <li class="ul__li"><a class="ul__link" href="{% url 'cart:cart' %}">Корзина</a></li>
                </ul>
            </nav>
        </header>
        <figure class="figure"> 
            <img class="img" src="{% static "images/main.jpg" %}">
        </figure>
    </body>
{% endblock %}