cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('main_cart', views.main_cart, name='cart'),

    path('create/<slug:slug>', views.create_cart, name='create_cart'),
    path('delete/<int:product_id>', views.delete_cart, name='delete_cart'),
    path('empty_cart', views.empty_cart, name='empty_cart'),
    path('order/', views.create_order, name='create_order'),
]

guitarst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('user.urls', namespace='user')),
]

from guitarst import settings

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from user.models import *
from catalog.models import *
from django.contrib.auth.models import User

# Модель корзины
class cart_Model(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name = 'Пользователь', db_constraint = False)
    user = models.CharField(max_length=120, null=True, verbose_name='Пользователь')
    product = models.CharField(max_length=120, verbose_name='Товар')
    price = models.IntegerField(null=True)
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    add_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления', null = True)

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    def __str__(self):
        return f'Корзина пользователя: {self.user} | Товар: {self.product} в количестве: {self.quantity}'
    
    def product_price(self):
        return round(self.price * self.quantity, 2)
    
    def total_quantity(self):
        return sum(product.quntity for product in self)
    

# Модель заказа
class order_Model(models.Model):
    phone_number = models.CharField(max_length=60, verbose_name='Номер телефона')
    first_name = models.CharField(max_length=120, verbose_name='Имя')
    last_name = models.CharField(max_length=120, verbose_name='Фамилия')
    address = models.CharField(max_length=120, verbose_name='Адрес доставки')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления')
    paid_choice = models.TextField(default=False, verbose_name='Оплата при получении')
    delivery_choice = models.TextField(default=False, verbose_name='Требуется доставка')
    status = models.CharField(max_length=30, default='В обработке')
    user = models.CharField(max_length=50, verbose_name='Пользователь', null=True)
    
    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ №: {self.pk} | пользователя: {self.user}'
    

class order_products_Model(models.Model):
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена товара', null=True)
    product = models.CharField(max_length=120, verbose_name='Товар', null=True)
    quantity = models.PositiveIntegerField(verbose_name='Количество', null=True)
    order = models.ForeignKey(to=order_Model, on_delete=models.CASCADE, verbose_name='Заказ', null=True)

    class Meta:
        verbose_name = 'Продукты заказа'
        verbose_name_plural = 'Продукты заказов'

cart/forms.py
from django import forms
from django.core.exceptions import ValidationError

class order_form(forms.Form):
    Paid_choice = (
        ('При получении', 'При получении'),
        ('Онлайн', 'Онлайн'),
    )

    Delivery_choice = (
        ('Самовывоз', 'Самовывоз'),
        ('Курьером', 'Курьером'),
    )

    phone_number = forms.CharField(max_length='60', label='Номер телефона', widget=forms.TextInput(attrs={'class': 'number_input', 'placeholder': 'Введите номер телефона'}))
    first_name = forms.CharField(max_length='120', label='Имя', widget=forms.TextInput(attrs={'class': 'first_input', 'placeholder': 'Введите ваше имя'}))
    last_name = forms.CharField(max_length='120', label='Фамилия', widget=forms.TextInput(attrs={'class': 'second_input', 'placeholder': 'Введите вашу фамилию'}))
    address = forms.CharField(max_length='120', label='Адрес доставки', widget=forms.TextInput(attrs={'class': 'addres_input', 'placeholder': 'Введите адрес доставки'}))
    paid_choice = forms.ChoiceField(label='Способ оплаты', choices=Paid_choice)
    delivery_choice = forms.ChoiceField(label='Способ доставки', choices=Delivery_choice)

    def clean_phone_number(self):# Валидация номера телефона
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры")
            
        if len(data) != 10 and data[0] != '+' or data[0] == '+' and len(data) != 11:
            
            self.add_error('phone_number', "Номер телефона должен содержать 10 цифр")
        return data
    
    def clean_first_name(self):# Валидация имени
        data = self.cleaned_data['first_name']
        alp = ["а","б","в","г","д","е","ё","ж","з","и","й","к","л","м","н","о",
            "п","р","с","т","у","ф","х","ц","ч","ш","щ","ъ","ы","ь","э","ю","я"]

        for i in data:
            if i not in alp:
                raise forms.ValidationError("Имя должно содержать только буквы")
        
        return data

    def clean_last_name(self):# Валидация фамилии
        data = self.cleaned_data['last_name']
        alp = ["а","б","в","г","д","е","ё","ж","з","и","й","к","л","м","н","о",
            "п","р","с","т","у","ф","х","ц","ч","ш","щ","ъ","ы","ь","э","ю","я"]

        for i in data:
            if i not in alp:
                raise forms.ValidationError("Фамилия должна содержать только буквы")
        
        return data

cart/views.py
from django.shortcuts import render, redirect
from .models import *
from catalog.models import *
from .forms import *
from django.db import transaction
from django.contrib import messages
from django.core.exceptions import *

# Основное отображение корзины
def main_cart(request):
    if cart_Model.objects.filter(user=request.user).count() != 0:

        user_cart = cart_Model.objects.filter(user=request.user)# корзина
        user_prices = cart_Model.objects.filter(user=request.user).values('price')# цены на товары
    
        full_price = 0# общая стоимость товаров в корзине
        for i in range(len(user_prices)):
            full_price += user_prices[i]['price']

        context = {
            'title': 'UserCart',
            'full_price': full_price,
            'user_cart': user_cart,
        }

        return render(request, 'main_cart.html', context)
    
    elif request.user.is_authenticated:
        context = {
            'title': 'Empty Cart',
        }

        return render(request, 'empty_cart.html', context)
    
    else:
        return redirect('user:reg_or_auth')


# Для пустой корзины
def empty_cart(request):
    return redirect('catalog:Main') # При нажатии на кнопку


# Создание корзины
def create_cart(request, slug):
    object = pproducts.objects.filter(slug=slug)# объект модели продуктов

    price = object.values('price')
    price = int(price[0]['price'])# цена товара

    product = object.values('name')[0]['name']# товар, добавляемый в коризну

    user_cart = cart_Model.objects.filter(user=request.user, product=product)# корзина пользователя
    
    if user_cart.exists():

        try:
            quantity = user_cart.values('quantity')
            quantity = quantity[0]['quantity']# количество товара
        except:
            print('Корзина не создана')

        user_product = user_cart.values('product')# товар в корзине

        if user_product[0]['product'] == product:
            quantity += 1
            user_cart.values('quantity').update(quantity=quantity)

    else:
       cart_Model.objects.create(product = product, quantity = 1, user = request.user, price = price)# создание записи в базе данных

    context = {
        'title': 'Cart',
        'text': 'Товар добавлен в корзину',
    }

    return render(request, 'cart.html', context)


# Удаление товара из корзины
def delete_cart(request, product_id):
    cart_Model.objects.filter(user=request.user, id=product_id).delete()

    return redirect(request.META['HTTP_REFERER'])



# Оформление и отображение заказа
def create_order(request):
    if request.method == 'POST':
        form = order_form(request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_objects = cart_Model.objects.filter(user=user)

                    order = order_Model.objects.create(
                        phone_number = form.cleaned_data['phone_number'],
                        first_name = form.cleaned_data['first_name'],
                        last_name = form.cleaned_data['last_name'],
                        address = form.cleaned_data['address'],
                        paid_choice = form.cleaned_data['paid_choice'],
                        delivery_choice = form.cleaned_data['delivery_choice'],
                        user = user,
                    )

                    for cart_object in cart_objects:
                        product = cart_object.product
                        price = cart_object.price
                        quantity = cart_object.quantity
                        product_quantity = pproducts.objects.filter(name=product).values('quantity')[0]['quantity']

                        if quantity > product_quantity:
                            raise ValidationError(f'Недостаточное количество товара {product} на складе\
                                                   В наличии - {quantity}')

                        else:

                            order_products_Model.objects.create(
                                product = product,
                                price = price,
                                quantity = quantity,
                                order = order,
                            )

                            new_product_quantity = product_quantity - quantity# Обновление количества товаров
                            pproducts.objects.filter(name=product).values('quantity').update(quantity=new_product_quantity)
                            cart_objects.delete()

                    messages.success(request, 'Заказ оформлен!')
                    return redirect('user:profile', user.pk)

            except ValidationError as e:
                messages.success(request, list(e)[0])
                return redirect('cart:create_order')
                
    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
        }

        form = order_form(initial=initial)

    context = {
        'form': form
    }

    return render(request, 'order.html', context)

cart/templates/cart.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/carts.css" %}">
{% endblock %}

{% block body %}
    <div class="add_text">
        <h1>{{ text }}</h1>
    </div>
{% endblock %}

cart/templates/empty_cart.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/carts.css" %}">
{% endblock %}

{% block body %}
    <form class="empty_card_form" action="{% url 'cart:empty_cart' %}">
        {% csrf_token %}
        <a class="empty_card_form__text"> В корзине нет товаров </a>
        <input class="empty_card_form__button" type="submit" value="Начать покупки">
    </form>
{% endblock %}

cart/templates/main_cart.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/carts.css" %}">
{% endblock %}

{% block body %}
    <h1 class="full_price">Сумма заказа: {{ full_price }}</h1>
    <div class="cart_objects">
        {% for cart_object in user_cart %}
            <h2 class="main_product_inf">Товар: {{ cart_object.product }} в количестве: {{ cart_object.quantity }} | {{ cart_object.product_price }}руб</h2>
            <form class="delete_form" action="{% url 'cart:delete_cart' cart_object.id %}" method="post">  
                {% csrf_token %}
                <button class="delete_form__button" type="submit">Удалить товар из корзины</button>
            </form>
        {% endfor %}
        <form class="show_order" action="{% url 'cart:create_order' %}">
            <button class="show_order__button" type="submit">Оформить заказ</button>
        </form>
    </div>
{% endblock %}

cart/templates/order.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static "css/carts.css" %}">
{% endblock %}

{% block body %}
<style>
    .success {
        font-family: 'JetBrains Mono', sans-serif;
        font-size: 30px;
        background: red; 
        display: flex ;
        justify-content: center;
    }

    .message_wrapper {
        width: 100%;
        float: left;
        margin: 0;
    }
</style>
<div class="message_wrapper">
    {% if messages %}
        {% for message in messages %}
            <div class="{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
</div>
<form class="order_form" action="{% url "cart:create_order" %}" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="form_group">
            {{ field.label }}
            {{ field }}
            {% if field.errors %}
                <div class="form_group__errors">{{ field.errors }}</div>
            {% endif %}
        </div>
    {% endfor %}
    <input class="order_form__input" type="submit" value="Оформить заказ"> 
</form>
{% endblock %}